/*DATAMIGRATION DC31DB21-8E87-49F9-A334-E7EB246DBD53*/ -- Change the script's code only if it needs to be executed again.

-- The following lines are generated by: EXEC Rhetos.HelpDataMigration 'Bookstore', 'Topic';
EXEC Rhetos.DataMigrationUse 'Bookstore', 'Topic', 'ID', 'uniqueidentifier';
EXEC Rhetos.DataMigrationUse 'Bookstore', 'Topic', 'Code', 'nvarchar(256)';
EXEC Rhetos.DataMigrationUse 'Bookstore', 'Topic', 'Name', 'nvarchar(256)';
GO

-- Initialize the new column "Code" with the generated numeric codes.
-- This is necessary to avoid the unique constraint error for multiple null values if any records exist in the table.

SELECT
    t.ID,
    NewCode = CAST(ROW_NUMBER() OVER (ORDER BY t.Name, t.ID) AS NVARCHAR(10))
INTO
    #codes
FROM
    _Bookstore.Topic t
WHERE
    t.Code IS NULL; -- Make sure to ignore already initialized values, if this script is executed multiple times.

UPDATE
    t
SET
    Code = c.NewCode
FROM
    _Bookstore.Topic t
    INNER JOIN #codes c ON c.ID = t.ID

EXEC Rhetos.DataMigrationApplyMultiple 'Bookstore', 'Topic', 'ID, Code';
